### ISSUE TITLE
Internationalize website

### ISSUE THREAD

**Issue by alltheseas** [damus-io/website#11]
@tyiu

**Comment by alltheseas** [comment]
@jb55 if we will use the website repo, can you give me the same permissions as the damus iOS github repo so I can build the project, add labels, milestones etc.

**Comment by jb55** [comment]
On Fri, Jun 30, 2023 at 08:53:19AM -0700, alltheseas wrote:
>@jb55 if we will use the website repo, can you give me the same permissions as the damus iOS github repo so I can build the project, add labels, milestones etc.

done
