### ISSUE TITLE
Damus.io/key css seems broken

### ISSUE THREAD

**Issue by alltheseas** [damus-io/website#19]
https://damus.io/key/

This page broken for anyone else? Seems like all the CSS is returning 404 for me.

**Comment by jb55** [comment]
On Sun, Feb 04, 2024 at 11:17:21AM -0800, alltheseas wrote:
>https://damus.io/key/
>
>This page broken for anyone else? Seems like all the CSS is returning 404 for me.

is this still needed in 2024?

**Comment by alltheseas** [comment]
I find a question about hex keys every couple of months on nostr. No idea which apps use.

I suggest lowest of priorities.
